# Generated by Django 5.2.13 on 2026-04-08 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('mood', models.CharField(choices=[('happy', '開心 😄'), ('calm', '平靜 😐'), ('anxious', '焦慮 😰'), ('sad', '低落 😢'), ('angry', '生氣 😡')], max_length=20, verbose_name='今日心情')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='原因與備註')),
            ],
        ),
    ]
