# Generated by Django 5.2.13 on 2026-04-08 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='moodrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='紀錄時間'),
        ),
    ]
